#!/usr/bin/env bash
# vim: set ft=sh :

main () {
    local path="${1}"
    local session="${2}"

    if [[ -z "${path}" ]]; then
        path="${PWD}"
    fi

    if [[ -z "${session}" ]]; then
        local session=$(basename "${path}")
    fi

    cd "${path}"

    tmux new-session -s "${session}" -n "${session}" -d

    if [[ -z "${TMUX}" ]]; then
        tmux attach -t "=${session}"
    else
        tmux switch-client -t "=${session}"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
