#!/usr/bin/env bash
# vim: set ft=sh :

main () {
    local path=$1

    if [[ -z $path ]]; then
        path=$PWD
    fi

    local session=$(basename $path)

    cd $path

    tmux new-session -s ${session} -n ${session} -d

    if [[ -z $TMUX ]]; then
        tmux attach -t ${session}
    else
        tmux switch-client -t ${session}
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
