#!/usr/bin/env bash
# vim: set ft=sh :

session_exists() {
    local folder_to_session="${1}"
    tmux has-session -t $(basename "${folder_to_session}")
}

switch_session() {
    local folder_to_session="${1}"
    tmux switch-client -t $(basename "${folder_to_session}")
}

create_session() {
    local folder_to_session="${1}"
    tmux new-session -s $(basename "${folder_to_session}") -n $(basename "${folder_to_session}") -d
}

attach_session() {
    local folder_to_session="${1}"
    tmux attach -t $(basename "${folder_to_session}")
}

in_tmux_session() {
    test -n "$TMUX"
}

get_folder_to_session() {
    local folder_to_search="${1}"

    if [[ -z "${folder_to_search}" ]]; then
        local folder_to_search="${HOME}"
    fi

    local all_folders=$(find "${folder_to_search}" -maxdepth 3 -type d  && zoxide query -l)
    echo  "${all_folders}" | fzf-tmux -p --preview 'tree -C {} | head -200'
}

main () {
    local folder_to_session=$(get_folder_to_session "${1}")

    cd "${folder_to_session}"

    if [[ -z "${folder_to_session}" ]]; then
        exit 0
    fi

    if in_tmux_session; then
        if session_exists "${folder_to_session}"; then
            switch_session "${folder_to_session}"
        else
            create_session "${folder_to_session}"
            switch_session "${folder_to_session}"
        fi
        exit 0
    else
        if session_exists "${folder_to_session}"; then
            attach_session "${folder_to_session}"
        else
            create_session "${folder_to_session}"
            attach_session "${folder_to_session}"
        fi
        exit 0
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "${@}"
fi
